// Generated by CoffeeScript 1.5.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Backbone.WorkflowArea = (function(_super) {

    __extends(WorkflowArea, _super);

    function WorkflowArea() {
      WorkflowArea.__super__.constructor.apply(this, arguments);
    }

    WorkflowArea.prototype.setupStateTransitionEvent = function() {
      return this.model.on("transition:to", this.changeState, this);
    };

    WorkflowArea.prototype.initialize = function() {
      return this.setupStateTransitionEvent();
    };

    WorkflowArea.prototype.changeState = function() {
      return false;
    };

    WorkflowArea.prototype.getActiveState = function() {
      return this.model.get('workflow_state');
    };

    return WorkflowArea;

  })(Backbone.View);

}).call(this);
